version: '{build}'

configuration: Release

environment:
  snk_secret:
    secure: 5q+Cyl0sRtamI4kHMyIGgRttc7aSjz+1iNbXcY3EpMNT98RYBp3/tY83y14RcNNC

install:
- nuget install secure-file -ExcludeVersion
- secure-file\tools\secure-file.exe -decrypt Regexp\Verophyle.snk.enc -secret %snk_secret%

build_script:
- msbuild Verophyle.Regexp.net45.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- msbuild Verophyle.Regexp.netstandard1.4.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cd Package
- nuget pack Regexp.nuspec -symbols

artifacts:
- path: Package\*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: zgS1RlHnfRi8sNKEkm2WqqNa9U7fYvJad8z5o0hNsP2VrOcUDuFsTsf28yFNOu0h
  skip_symbols: false
  artifact: /.*\.nupkg/
