version: "2.1.1.{build}"

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - master

image: Visual Studio 2017

configuration: Release

environment:
  snk_secret:
    secure: 5q+Cyl0sRtamI4kHMyIGgRttc7aSjz+1iNbXcY3EpMNT98RYBp3/tY83y14RcNNC

install:
- if defined snk_secret (nuget install secure-file -ExcludeVersion)
- if defined snk_secret (secure-file\tools\secure-file.exe -decrypt Verophyle.Regexp\Verophyle.snk.enc -secret %snk_secret%)
- if not defined snk_secret (copy Verophyle.Regexp\Verophyle.PRS.snk Verophyle.Regexp\Verophyle.snk)

before_build:
- nuget restore

build:
  verbosity: minimal

artifacts:
- path: '**\*.nupkg'

deploy:
  provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key:
    secure: zgS1RlHnfRi8sNKEkm2WqqNa9U7fYvJad8z5o0hNsP2VrOcUDuFsTsf28yFNOu0h
  skip_symbols: false
  artifact: /.*\.nupkg/
