version: '{build}'
configuration: Release
environment:
  key_secret: D2DE09A4-367A-4222-9816-9C7C9D924A5C
install:
- cmd: >-
    nuget install secure-file -ExcludeVersion
    secure-file\tools\secure-file -decrypt Regexp\Verophyle.snk.enc -secret %key_secret%
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
artifacts:
- path: Package\*.nupkg